### ISSUE TITLE
Do you use MSMS data anywhere in the pipeline?

### ISSUE THREAD

**Issue by eterlova** [plyush1993/OUKS#1]
Hello all,

Just a quick question about what to do with the MSMS data. I am working with Waters MS/MSe data set, and trying to find a good way to annotate it hopefully leveraging both MS and MSe data to improve annotation. 

Sinse in your pipeline you use CAMERA package (only operates on MS data), and you filter out MSMS to use RAMClustR, do you end up only with annotation based on MS spectra?

Best,
Lisa

**Comment by plyush1993** [comment]
Hello, Lisa!
Thank you for your interest in my software.
Quick response is no: my software currently incorporates only MS1 data. For simultaneous integration of both MS1 and MS2 and other related information, I firstly can recommend [xcms](https://www.bioconductor.org/packages/devel/bioc/vignettes/xcms/inst/doc/xcms-lcms-ms.html), [MS-DIAL](https://mtbinfo-team.github.io/mtbinfo.github.io/MS-DIAL/tutorial#chapter-2), [MzMine3](http://mzmine.github.io/), [patRoon](https://github.com/rickhelmus/patRoon), [PMDDA](https://yufree.github.io/pmdda/script.html) and [xcmsrocker](https://github.com/yufree/xcmsrocker).  
In my pipeline signal annotation is performed only by features, that can obtained from peak table (_m/z_ values, ret. time and intensities). 
For simultaneous MS1 and MS2 annotation you can use parameter "idmsms" in function "ramclustR" (package [RAMClustR](https://cran.r-project.org/web/packages/RAMClustR/index.html)), or [metID](https://jaspershen.github.io/metID/articles/metabolite_annotation_using_MS2.html). Moreover, you can also use [CluMSID](https://www.bioconductor.org/packages/release/bioc/html/CluMSID.html), [MetaboAnnotation](https://www.bioconductor.org/packages/devel/bioc/html/MetaboAnnotation.html), [MS2Analyzer](https://fiehnlab.ucdavis.edu/projects/MS2Analyzer/).

Please feel free to contact me with any questions.
Best regards,
Ivan

**Comment by eterlova** [comment]
Thanks a lot for a prompt reply and the advice! I know it's a lot to ask, but do you think you could talk with me over zoom or Skype about my data and the avenues for the analysis? I have tried some of the packages you mentioned, but cannot get beyond MS1 level identification

**Comment by plyush1993** [comment]
Please, write me to e-mail (plyushchenko.ivan@gmail.com). So, the issue will be closed.

**Comment by eterlova** [comment]
Will do! thanks a lot
